config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :hospitals do
      post 'remove_doctor', on: :member
  end    

  root 'hospitals#index'


end

app/models/doctor.rb
class Doctor < ActiveRecord::Base 
  validates :name, :year, :title, presence: true
  TITLES = [ "медсестра", "фельдшер", "врач" ]
  validates :title, inclusion: TITLES
  YEARS = (1945..2016).to_a.reverse!
  validates :year, inclusion: YEARS
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	attr_accessor :doctors_list
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show]

  def index
    @doctors = Doctor.all
  end

  def new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor,
          notice: 'Staff was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def show
  end

  def update
    @doctor = Doctor.find(params[:id])
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor,
          notice: 'Doctor was successfully updated.' }
          format.json { head :no_content }
      else
        format.html { render action: 'edit' }
      end
    end
  end   

  private

  def set_doctor
    @doctor = DoctorDecorator.decorate(Doctor.find(params[:id]))
  end

  def doctor_params
    params.require(:doctor).permit(:name, :year, :title)
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :remove_doctor]

  def index
    @hospitals = Hospital.all
  end

  def new
  end

  def create
    @hospital = Hospital.new(hospital_params)

    if @hospital.save
      redirect_to '/'
    else
      render action: 'new' 
    end  
  end

  def edit
  end

  def update
    notice = SHospital::Update.new(@hospital, params).main
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to :back, notice: notice }
      end
    end
  end

  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy
  end

  def remove_doctor
    notice = SHospital::RemoveDoctor.new(@hospital, params).main
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to :back, notice: notice }
      end
    end
  end

  private

  def set_hospital
    @hospital = HospitalDecorator.decorate(Hospital.find(params[:id]))
  end

  def hospital_params
    params.require(:hospital).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/doctors/index.html.erb
<div class="container">
  <br/>
  <%= link_to 'New staff', new_doctor_path %>
  <h3>Список сотрудников</h3>

  <table>
    <thead>
      <tr>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.id %></td>
          <td><%= link_to  doctor.name, doctor_path(doctor) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Все больницы', '/hospitals' %>

app/views/doctors/new.html.erb
<div class="container">
  <h3>Новый сотрудник</h3>
  <%= form_for :doctor, url: doctors_path do |f| %>
    <label>Фамилия</label><br/>
    <div class="field">
      <%= f.text_field :name, class: "form-control" %>
    </div><br/>

    <label>Год рождения</label><br/>
    <div class="field">
      <%= f.select :year, Doctor::YEARS, class: "form-control" %>
    </div><br/>
 
    <label>Должность</label><br/>
    <div class="field">
      <%= f.select :title, Doctor::TITLES, class: "form-control" %>
    </div><br/>
    
    <%= f.submit 'Создать', :class => 'btn btn-primary' %>
    
  <% end %>
</div>

app/views/doctors/show.html.erb
<div class="container">
	<h2>Профиль</h2>
  <div>Фамилия: <b><%= @doctor.name %></b></div>
  <div>Год рождения: <b><%= @doctor.year %></b></div>
  <div>Должность: <b><%= @doctor.title %></b></div>
  <br/>
  <h4>Список больниц, в которых работает этот доктор</h4>
	<table>
	  <tr>
	    <td>Имя</td>
	    <td>Действие</td>
	  </tr>
	  <% @doctor.has_hospitals.each do |element| %>
	  <tr>
	    <td><%= element.name  %></td>
	    <td><%= link_to "посмотреть", edit_hospital_path(element) %></td>
	  </tr>
	  <% end %>
  </table>
  <hr/>
  <i>Редактировать</i><br/>
  <%= form_for(@doctor) do |f| %>
      <%= f.text_field :name %>
      <%= f.select :year, Doctor::YEARS, class: "form-control" %>
       <%= f.select :title, Doctor::TITLES, class: "form-control" %>
      <%= f.submit "Обновить профиль", :class => "btn" %>
    <% end %> 


  <%= link_to 'К списку больниц', hospitals_path %>
  <%= link_to 'К списку докторов', doctors_path %>
</div>

app/views/hospitals/edit.html.erb
<div class="container">
  <h3><%= @hospital.name %></h3>
  <i>Режим редактирования</i><br/>
  <i><%= flash[:notice] %></i>

  <table>
	  <tr>
	    <td>Имя</td>
	    <td>Действие</td>
	  </tr>
  	<% @hospital.personal.each do |element| %>
	  <tr>
	    <td><%= link_to element.name, doctor_path(element) %></td>
	    <td><%= button_to "Удалить",{action: "remove_doctor", doctor_id: element.id} %></td>
	  </tr>
	  <% end %>
  </table>
  <hr/>
  <table>
  <%= form_for(@hospital) do |f| %>
  	<tr>
	    <td><%= f.select(:doctors_list, options_for_select(@hospital.avaible_doctors)) %></td>
	    <td><%= f.submit "Добавить" %></td>
	  </tr>
  <% end %>	
  </table>

  <%= link_to 'Назад', @hospital %> |
  <%= link_to 'К списку больниц', hospitals_path %>
</div>

app/views/hospitals/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <%= link_to 'Добавить Больницу', new_hospital_path %>
  <h3>Все больницы</h3>

  <table>
    <thead>
      <tr>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @hospitals.each do |hospital| %>
        <tr>
          <td><%= hospital.id %></td>
          <td><%=  hospital.name %></td>
          <td><%= link_to 'Редактировать', edit_hospital_path(hospital) %>
          <%= link_to 'Удалить', hospital_path(hospital), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Все врачи', '/doctors' %>
</div>

app/views/hospitals/new.html.erb
<div class="container">
  <h3>New Hospital</h3>
  <%= form_for :hospital, url: hospitals_path do |f| %>
  <p> 
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p> 
    <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>SimpleApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">На Главную</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/">Все Больницы</a></li>
            <li><a href="/doctors">Все сотрудники</a></li>
            <li><a href="/doctors/new">Добавить нового сотрудника</a></li>
            <li><a href="/hospitals/new">Добавить Больницу</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>